= api-sheriff

== Status

image:https://github.com/cuioss/api-sheriff/actions/workflows/maven.yml/badge.svg[Java CI with Maven,link=https://github.com/cuioss/api-sheriff/actions/workflows/maven.yml]
image:http://img.shields.io/:license-apache-blue.svg[License,link=http://www.apache.org/licenses/LICENSE-2.0.html]
image:https://img.shields.io/maven-central/v/de.cuioss.sheriff.api/api-sheriff.svg?label=Maven%20Central["Maven Central", link="https://central.sonatype.com/artifact/de.cuioss.sheriff.api/api-sheriff"]

https://sonarcloud.io/summary/new_code?id=cuioss_API-Sheriff[image:https://sonarcloud.io/api/project_badges/measure?project=cuioss_API-Sheriff&metric=alert_status[Quality
Gate Status]]
image:https://sonarcloud.io/api/project_badges/measure?project=cuioss_API-Sheriff&metric=ncloc[Lines of Code,link=https://sonarcloud.io/summary/new_code?id=cuioss_API-Sheriff]
image:https://sonarcloud.io/api/project_badges/measure?project=cuioss_API-Sheriff&metric=coverage[Coverage,link=https://sonarcloud.io/summary/new_code?id=cuioss_API-Sheriff]


https://cuioss.github.io/cui-java-module-template/about.html[Generated Documentation on github-pages]

== What is it?



=== Maven Coordinates

[source,xml]
----
    <dependency>
        <groupId>de.cuioss.sheriff.api</groupId>
        <artifactId>api-sheriff-parent</artifactId>
    </dependency>
----

=== Credentials

Add the necessary credentials to the project: "Settings" -> "Secrets" -> "Actions", as there are: 

* `SONAR_TOKEN` -> Sonar-Cloud

They are picked up in the predefined pipeline-configurations:

* `.github/workflows/maven.yml`
* `.github/workflows/maven-release.yml`

Ensure that the actions are authorized correctly: Settings > Actions > General > Workflow permissions >  "Read and write permissions" must be selected *not* "Read repository contents permission"

Documentation on how to create a signing key can be found https://github.com/cuioss/cui-parent-pom/blob/master/doc/signing_key.adoc[Documentation at cui-parent-pom] 

A sonar token can be derived from https://sonarcloud.io/account/security

=== Further Steps

* Verify that the customization was applied correctly to all files
* If you're using manual customization:
** `pom.xml`: Adjust `name` and `description` elements
** Adjust `module-info` accordingly
** `pom.xml`: Adjust property `maven.jar.plugin.automatic.module.name` according to your `module-info`
* `src/site/asciidoc/about.adoc`: Adjust content
* Review / Enable the elements under 'Security' Tab
* Review / Add Collaborators
* Add (link) the resulting maven-documentation: https://github.com/cuioss/cuioss.github.io/edit/main/README.md[github.io-documentation]

=== Customization Properties
