#!/bin/bash
# Generates the server certificate pair of the one-off generated-keys gateway (BffGeneratedKeysIT):
#
#   generated-keys-gateway.crt  the self-signed certificate that gateway presents
#   generated-keys-gateway.key  its private key
#
# WHY THIS GATEWAY HAS A CERTIFICATE OF ITS OWN. Keycloak fetches the gateway's generated client key
# from https://sheriff-generated-keys:8443/auth/client-keys and verifies the host name it dials. The
# stack certificate (localhost.crt) covers api-sheriff and no other gateway name, so a gateway
# reached under the network alias sheriff-generated-keys cannot present it. The SAN list below names
# that alias, plus localhost and 127.0.0.1, under which the test JVM reaches the published port.
#
# WHY A SEPARATE SCRIPT. generate-certificates.sh rewrites the stack certificate pair and the
# upstream-mismatch pair, and generate-truststore.sh derives the two trust stores from those
# certificates. Adding this pair there would regenerate all of that to produce one more file. This
# script writes the two files named above and nothing else, so localhost.crt, localhost.key and both
# trust stores stay byte-identical.
#
# TEST MATERIAL. Both files are committed and the key is unencrypted and world-readable on purpose:
# the gateway image runs as its own non-root user and reads the bind-mounted key as that user. The
# pair serves one throwaway container on the integration network. Never use it outside this stack.
#
# The pair is trusted by exactly one party: the Keycloak service of docker-compose.yml lists the
# certificate in KC_TRUSTSTORE_PATHS. Regenerating it needs no other edit — Keycloak reads the file
# from the mounted certificates directory at its next start.
#
# The certificate is valid for 730 days, like the stack certificate beside it. It is committed, not
# generated by the build, so it has to be regenerated by hand before it expires.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
CERTIFICATE="${SCRIPT_DIR}/generated-keys-gateway.crt"
PRIVATE_KEY="${SCRIPT_DIR}/generated-keys-gateway.key"
VALIDITY_DAYS=730

echo "Generating the generated-keys gateway certificate pair in ${SCRIPT_DIR}..."

rm -f "${CERTIFICATE}" "${PRIVATE_KEY}"

openssl req -x509 -newkey rsa:2048 -nodes -days "${VALIDITY_DAYS}" \
  -keyout "${PRIVATE_KEY}" -out "${CERTIFICATE}" \
  -subj "/CN=sheriff-generated-keys/OU=Integration Testing/O=API-Sheriff/L=Berlin/ST=Berlin/C=DE" \
  -addext "subjectAltName=DNS:sheriff-generated-keys,DNS:localhost,IP:127.0.0.1"

# Readable by the container's non-root user. The key protects nothing outside this stack.
chmod 644 "${CERTIFICATE}" "${PRIVATE_KEY}"

echo "Generated:"
echo "  - $(basename "${CERTIFICATE}") (SAN: sheriff-generated-keys, localhost, 127.0.0.1)"
echo "  - $(basename "${PRIVATE_KEY}")"
echo "No other file was written."
