/*
 * Copyright © 2025-present CUI-OpenSource-Software (info@cuioss.de)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package de.cuioss.sheriff.gateway.bff.client;

import static org.junit.jupiter.api.Assertions.assertAll;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotEquals;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.junit.jupiter.api.Assumptions.assumeFalse;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.security.GeneralSecurityException;
import java.security.KeyPair;
import java.security.PrivateKey;
import java.security.PublicKey;
import java.security.Signature;
import java.security.spec.MGF1ParameterSpec;
import java.security.spec.PSSParameterSpec;
import java.util.Base64;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Set;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import de.cuioss.sheriff.gateway.bff.BffLogMessages;
import de.cuioss.sheriff.gateway.bff.client.ClientSigningKey.Mode;
import de.cuioss.sheriff.gateway.bff.client.ClientSigningKey.Purpose;
import de.cuioss.sheriff.token.client.auth.PrivateKeyJwtAuth;
import de.cuioss.sheriff.token.client.dpop.DpopProofGenerator;
import de.cuioss.sheriff.token.client.dpop.SenderConstraint;
import de.cuioss.sheriff.token.validation.util.JwkThumbprintUtil;
import de.cuioss.test.generator.Generators;
import de.cuioss.test.generator.junit.EnableGeneratorController;
import de.cuioss.test.juli.TestLogLevel;
import de.cuioss.test.juli.TestLoggerFactory;
import de.cuioss.test.juli.junit5.EnableTestLogger;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.condition.EnabledOnOs;
import org.junit.jupiter.api.condition.OS;
import org.junit.jupiter.api.io.TempDir;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.EnumSource;

/**
 * Tests for {@link ClientSigningKey} — the two signing-key modes of the confidential client.
 * <p>
 * The contracts under test are: the generated mode yielding a fresh EC P-256 key per resolution and
 * recording it without any key member; the provided mode deriving the algorithm from the key type;
 * the key id being the thumbprint the token engine computes for the same key, so the gateway's JWK
 * rendering and the engine's cannot drift; the published JWK carrying public signature members only;
 * the key reaching the engine's client assertion and DPoP proof; every refusal staged here naming the
 * configuration field while echoing neither the configured path nor a line of the file; and the
 * absence of any key member from {@link ClientSigningKey#toString()}.
 * <p>
 * Every provided key is generated by {@link TestSigningKeys} inside the test; none is read from a
 * committed file.
 */
@EnableTestLogger
@EnableGeneratorController
class ClientSigningKeyTest {

    private static final String GENERATED_KEY_RECORD =
            BffLogMessages.INFO.SIGNING_KEY_GENERATED.resolveIdentifierString();
    private static final String CLIENT_AUTHENTICATION_FIELD = "oidc.client_authentication.key_file";
    private static final String SENDER_CONSTRAINT_FIELD = "oidc.sender_constraint.key_file";
    private static final List<String> PRIVATE_JWK_MEMBERS = List.of("d", "p", "q", "dp", "dq", "qi", "oth", "k");
    private static final ObjectMapper JSON = new ObjectMapper();

    @TempDir
    Path directory;

    /** The two accepted key types, each with the algorithm and the JWK shape it must yield. */
    enum KeyType {

        RSA("PS256", List.of("kty", "use", "alg", "kid", "n", "e")) {
        @Override
        KeyPair generate() {
            return TestSigningKeys.rsaKeyPair();
        }

        @Override
        Signature joseVerifier() throws GeneralSecurityException {
            Signature verifier = Signature.getInstance("RSASSA-PSS");
            verifier.setParameter(new PSSParameterSpec("SHA-256", "MGF1", MGF1ParameterSpec.SHA256, 32, 1));
            return verifier;
        }
    },

        EC("ES256", List.of("kty", "use", "alg", "kid", "crv", "x", "y")) {
            @Override
            KeyPair generate() {
                return TestSigningKeys.ecKeyPair();
            }

            @Override
            Signature joseVerifier() throws GeneralSecurityException {
                return Signature.getInstance("SHA256withECDSAinP1363Format");
            }
        };

        private final String algorithm;
        private final List<String> jwkMembers;

        KeyType(String algorithm, List<String> jwkMembers) {
            this.algorithm = algorithm;
            this.jwkMembers = jwkMembers;
        }

        abstract KeyPair generate();

        abstract Signature joseVerifier() throws GeneralSecurityException;
    }

    private ClientSigningKey provided(KeyPair keyPair, Purpose purpose) {
        return ClientSigningKey.resolve(TestSigningKeys.writeKeyFile(directory, keyPair).toString(), purpose);
    }

    private static int infoRecordsContaining(String part) {
        return TestLoggerFactory.getTestHandler().resolveLogMessagesContaining(TestLogLevel.INFO, part).size();
    }

    private static JsonNode jwtPart(String compactJwt, int index) throws IOException {
        return JSON.readTree(Base64.getUrlDecoder().decode(compactJwt.split("\\.")[index]));
    }

    private static boolean verifies(String compactJwt, Signature verifier, PublicKey publicKey)
            throws GeneralSecurityException {
        int signatureStart = compactJwt.lastIndexOf('.');
        verifier.initVerify(publicKey);
        verifier.update(compactJwt.substring(0, signatureStart).getBytes(StandardCharsets.US_ASCII));
        return verifier.verify(Base64.getUrlDecoder().decode(compactJwt.substring(signatureStart + 1)));
    }

    /** Asserts a refusal decided on the path alone: the field is named, the path is not echoed. */
    private static void assertPathRefusal(String configured, String field, Purpose purpose, String defect) {
        IllegalStateException thrown = assertThrows(IllegalStateException.class,
                () -> ClientSigningKey.resolve(configured, purpose), "the key file should be refused");

        String message = thrown.getMessage();
        assertAll("refusal of " + defect,
                () -> assertTrue(message.startsWith(field + " "), "the refusal should name the field: " + message),
                () -> assertTrue(message.contains(defect), "the refusal should name the defect: " + message),
                () -> assertFalse(message.contains(configured), "the configured path should never be echoed"),
                () -> assertNull(thrown.getCause(), "no cause should be chained, a JDK failure text carries the path"));
    }

    /** Asserts a refusal decided on the file content of the client-authentication key. */
    private static void assertContentRefusal(Path keyFile, String defect) throws IOException {
        assertContentRefusal(keyFile, Purpose.CLIENT_AUTHENTICATION, CLIENT_AUTHENTICATION_FIELD, defect);
    }

    /** Asserts a refusal decided on the file content: additionally, no line of the file is echoed. */
    private static void assertContentRefusal(Path keyFile, Purpose purpose, String field, String defect)
            throws IOException {
        List<String> contentLines = Files.readAllLines(keyFile, StandardCharsets.US_ASCII).stream()
                .filter(line -> !line.isBlank() && !line.startsWith("-----"))
                .toList();
        String configured = keyFile.toString();

        IllegalStateException thrown = assertThrows(IllegalStateException.class,
                () -> ClientSigningKey.resolve(configured, purpose),
                "the key file should be refused");

        String message = thrown.getMessage();
        assertAll("refusal of " + defect,
                () -> assertTrue(message.startsWith(field + " "),
                        "the refusal should name the field: " + message),
                () -> assertTrue(message.contains(defect), "the refusal should name the defect: " + message),
                () -> assertFalse(message.contains(configured), "the configured path should never be echoed"),
                () -> assertFalse(contentLines.isEmpty(), "the fixture should hold content that could leak"),
                () -> assertTrue(contentLines.stream().noneMatch(message::contains),
                        "no line of the key file should be echoed: " + message),
                () -> assertNull(thrown.getCause(), "no cause should be chained, it could carry file content"));
    }

    @Nested
    @DisplayName("Generated mode")
    class GeneratedMode {

        @Test
        @DisplayName("Should generate an ES256 key when no key file is configured")
        void shouldGenerateAnEs256Key() {
            ClientSigningKey key = ClientSigningKey.resolve(null, Purpose.CLIENT_AUTHENTICATION);

            assertAll("generated key",
                    () -> assertEquals(Mode.GENERATED, key.mode(), "the mode should be reported as generated"),
                    () -> assertEquals("ES256", key.algorithm(), "a generated key should sign ES256"),
                    () -> assertEquals(KeyType.EC.jwkMembers, List.copyOf(key.publicJwk().keySet()),
                            "a generated key should publish the EC P-256 members"));
        }

        @Test
        @DisplayName("Should generate a distinct key per resolution, so a restart changes the key id")
        void shouldGenerateADistinctKeyPerResolution() {
            ClientSigningKey first = ClientSigningKey.resolve(null, Purpose.CLIENT_AUTHENTICATION);
            ClientSigningKey second = ClientSigningKey.resolve(null, Purpose.CLIENT_AUTHENTICATION);

            assertNotEquals(first.keyId(), second.keyId(), "each resolution should yield its own key id");
        }

        @Test
        @DisplayName("Should derive the key id the engine's DpopProofGenerator.jkt() reports for the generated pair")
        void shouldDeriveTheEngineThumbprintForAGeneratedKey() {
            ClientSigningKey key = ClientSigningKey.resolve(null, Purpose.SENDER_CONSTRAINT);

            SenderConstraint constraint = key.senderConstraint();

            assertEquals(constraint.binding().confirmation(), key.keyId(),
                    "the key id should equal the jkt the engine computed over the same key pair");
        }

        @Test
        @DisplayName("Should record the generated key once, with the purpose label and no key member")
        void shouldRecordTheGeneratedKeyWithoutKeyMaterial() {
            ClientSigningKey key = ClientSigningKey.resolve(null, Purpose.CLIENT_AUTHENTICATION);

            assertAll("generated-key record",
                    () -> assertEquals(1, infoRecordsContaining(GENERATED_KEY_RECORD), "one record per generated key"),
                    () -> assertEquals(1, infoRecordsContaining("Signing key for client-authentication generated "
                            + "at startup (generated on startup)"), "the record should carry purpose and mode"),
                    () -> assertEquals(0, infoRecordsContaining(key.keyId()), "the key id should not be logged"),
                    () -> assertEquals(0, infoRecordsContaining((String) key.publicJwk().get("x")),
                            "no public member should be logged"),
                    () -> assertEquals(0, infoRecordsContaining((String) key.publicJwk().get("y")),
                            "no public member should be logged"));
        }

        @Test
        @DisplayName("Should record the sender-constraint purpose under its own label")
        void shouldRecordTheSenderConstraintPurpose() {
            ClientSigningKey.resolve(null, Purpose.SENDER_CONSTRAINT);

            assertEquals(1, infoRecordsContaining("Signing key for sender-constraint generated at startup"),
                    "the record should carry the sender-constraint label");
        }
    }

    @Nested
    @DisplayName("Provided mode")
    class ProvidedMode {

        @ParameterizedTest
        @EnumSource(KeyType.class)
        @DisplayName("Should sign with the algorithm the key type determines, and record no generated key")
        void shouldDeriveTheAlgorithmFromTheKeyType(KeyType keyType) {
            ClientSigningKey key = provided(keyType.generate(), Purpose.CLIENT_AUTHENTICATION);

            assertAll("provided " + keyType + " key",
                    () -> assertEquals(Mode.PROVIDED, key.mode(), "the mode should be reported as provided"),
                    () -> assertEquals(keyType.algorithm, key.algorithm(), "the algorithm should follow the key type"),
                    () -> assertEquals(0, infoRecordsContaining(GENERATED_KEY_RECORD),
                            "a provided key should not be recorded as generated"));
        }

        @ParameterizedTest
        @EnumSource(KeyType.class)
        @DisplayName("Should derive the key id DpopProofGenerator.jkt() reports for the same key pair")
        void shouldDeriveTheEngineThumbprintForAProvidedKey(KeyType keyType) {
            KeyPair keyPair = keyType.generate();
            String engineThumbprint = new DpopProofGenerator(keyPair, keyType.algorithm).jkt();

            ClientSigningKey key = provided(keyPair, Purpose.CLIENT_AUTHENTICATION);

            assertEquals(engineThumbprint, key.keyId(), "the key id should be the engine's RFC 7638 thumbprint");
        }

        @ParameterizedTest
        @EnumSource(KeyType.class)
        @DisplayName("Should publish a JWK with use sig, no key_ops and no private member")
        void shouldPublishPublicSignatureMembersOnly(KeyType keyType) {
            ClientSigningKey key = provided(keyType.generate(), Purpose.CLIENT_AUTHENTICATION);

            Map<String, Object> jwk = key.publicJwk();

            assertAll("public JWK of a " + keyType + " key",
                    () -> assertEquals(keyType.jwkMembers, List.copyOf(jwk.keySet()),
                            "the members should be published in their fixed order"),
                    () -> assertEquals("sig", jwk.get("use"), "the key should be published for signatures"),
                    () -> assertEquals(keyType.algorithm, jwk.get("alg"), "the algorithm should be published"),
                    () -> assertEquals(key.keyId(), jwk.get("kid"), "the key id should be published"),
                    () -> assertFalse(jwk.containsKey("key_ops"), "no key_ops member should be published"),
                    () -> assertTrue(PRIVATE_JWK_MEMBERS.stream().noneMatch(jwk::containsKey),
                            "no private member should be published"),
                    () -> assertThrows(UnsupportedOperationException.class, () -> jwk.put("d", "leak"),
                            "the published JWK should be unmodifiable"));
        }

        @ParameterizedTest
        @EnumSource(KeyType.class)
        @DisplayName("Should hand the key to a client assertion that carries kid, alg and a string audience and verifies")
        void shouldSignAVerifiableClientAssertion(KeyType keyType) throws Exception {
            KeyPair keyPair = keyType.generate();
            String clientId = Generators.letterStrings(8, 24).next();
            String audience = "https://" + Generators.letterStrings(5, 12).next().toLowerCase(Locale.ROOT)
                    + ".example/realms/main";
            ClientSigningKey key = provided(keyPair, Purpose.CLIENT_AUTHENTICATION);
            Map<String, String> form = new HashMap<>();

            key.clientAuthentication(clientId, audience).decorate(form, new HashMap<>());

            String assertion = form.get("client_assertion");
            JsonNode header = jwtPart(assertion, 0);
            JsonNode claims = jwtPart(assertion, 1);
            assertAll("client assertion of a " + keyType + " key",
                    () -> assertEquals(key.keyId(), header.path("kid").asText(), "the header should carry the key id"),
                    () -> assertEquals(keyType.algorithm, header.path("alg").asText(),
                            "the header should carry the algorithm"),
                    () -> assertTrue(claims.path("aud").isTextual(), "the audience should be one JSON string"),
                    () -> assertEquals(audience, claims.path("aud").asText(), "the audience should be passed through"),
                    () -> assertEquals(clientId, claims.path("iss").asText(), "the issuer should be the client id"),
                    () -> assertTrue(verifies(assertion, keyType.joseVerifier(), keyPair.getPublic()),
                            "the assertion should verify against the public half"));
        }

        @ParameterizedTest
        @EnumSource(KeyType.class)
        @DisplayName("Should hand the key to a DPoP proof whose embedded JWK has the key id as its thumbprint")
        void shouldBindDpopProofsToTheKeyId(KeyType keyType) throws Exception {
            KeyPair keyPair = keyType.generate();
            String tokenEndpoint = "https://" + Generators.letterStrings(5, 12).next().toLowerCase(Locale.ROOT)
                    + ".example/token";
            ClientSigningKey key = provided(keyPair, Purpose.SENDER_CONSTRAINT);
            Map<String, String> headers = new HashMap<>();

            key.senderConstraint().apply("POST", tokenEndpoint, headers);

            String proof = headers.get("DPoP");
            JsonNode header = jwtPart(proof, 0);
            Map<String, Object> embeddedJwk = JSON.convertValue(header.path("jwk"), new TypeReference<>() {
            });
            assertAll("DPoP proof of a " + keyType + " key",
                    () -> assertEquals(key.keyId(), JwkThumbprintUtil.computeThumbprint(embeddedJwk),
                            "the embedded JWK's thumbprint should equal the key id"),
                    () -> assertEquals(keyType.algorithm, header.path("alg").asText(),
                            "the proof should be signed with the key's algorithm"),
                    () -> assertTrue(verifies(proof, keyType.joseVerifier(), keyPair.getPublic()),
                            "the proof should verify against the public half"));
        }
    }

    @Nested
    @DisplayName("Refusal of an unusable key file")
    class FileRefusal {

        @Test
        @DisplayName("Should refuse a missing file")
        void shouldRefuseAMissingFile() {
            String missing = directory.resolve("absent.pem").toString();

            assertPathRefusal(missing, CLIENT_AUTHENTICATION_FIELD, Purpose.CLIENT_AUTHENTICATION,
                    "names a file that does not exist");
        }

        @Test
        @DisplayName("Should name the sender-constraint field for the sender-constraint purpose")
        void shouldNameTheFieldOfThePurpose() {
            String missing = directory.resolve("absent.pem").toString();

            assertPathRefusal(missing, SENDER_CONSTRAINT_FIELD, Purpose.SENDER_CONSTRAINT,
                    "names a file that does not exist");
        }

        @Test
        @DisplayName("Should refuse a directory, which is not a regular file")
        void shouldRefuseANonRegularFile() {
            assertPathRefusal(directory.toString(), CLIENT_AUTHENTICATION_FIELD, Purpose.CLIENT_AUTHENTICATION,
                    "does not name a regular file");
        }

        @Test
        @EnabledOnOs({OS.LINUX, OS.MAC})
        @DisplayName("Should refuse an unreadable file")
        void shouldRefuseAnUnreadableFile() throws Exception {
            Path keyFile = TestSigningKeys.writeKeyFile(directory, TestSigningKeys.ecKeyPair());
            Files.setPosixFilePermissions(keyFile, Set.of());
            assumeFalse(Files.isReadable(keyFile), "this user reads any file, so the case cannot be staged");

            assertPathRefusal(keyFile.toString(), CLIENT_AUTHENTICATION_FIELD, Purpose.CLIENT_AUTHENTICATION,
                    "names a file that cannot be read");
        }

        @Test
        @DisplayName("Should refuse a path the platform cannot represent")
        void shouldRefuseAnUnusablePath() {
            assertPathRefusal("key\0file.pem", CLIENT_AUTHENTICATION_FIELD, Purpose.CLIENT_AUTHENTICATION,
                    "does not name a usable file path");
        }

        @Test
        @DisplayName("Should refuse a file above the 16 KiB bound without parsing it")
        void shouldRefuseAnOversizeFile() throws Exception {
            KeyPair keyPair = TestSigningKeys.ecKeyPair();
            String padding = "\n".repeat(ClientSigningKey.MAX_KEY_FILE_BYTES);
            Path keyFile = TestSigningKeys.writeContent(directory, TestSigningKeys.privateBlock(keyPair.getPrivate())
                    + TestSigningKeys.publicBlock(keyPair.getPublic()) + padding);

            assertContentRefusal(keyFile, "names a file larger than the 16384 byte limit");
        }

        @Test
        @DisplayName("Should reject a missing purpose rather than resolving an unnamed key")
        void shouldRejectAMissingPurpose() {
            assertThrows(NullPointerException.class, () -> ClientSigningKey.resolve(null, null),
                    "a purpose should be required");
        }
    }

    @Nested
    @DisplayName("Refusal of a malformed block set")
    class BlockRefusal {

        @Test
        @DisplayName("Should refuse a file with no PUBLIC KEY block")
        void shouldRefuseAPrivateBlockOnly() throws Exception {
            assertContentRefusal(TestSigningKeys.writePrivateBlockOnly(directory, TestSigningKeys.ecKeyPair()),
                    "holds no PUBLIC KEY block");
        }

        @Test
        @DisplayName("Should refuse a file with no PRIVATE KEY block")
        void shouldRefuseAPublicBlockOnly() throws Exception {
            assertContentRefusal(TestSigningKeys.writePublicBlockOnly(directory, TestSigningKeys.ecKeyPair()),
                    "holds no PRIVATE KEY block");
        }

        @Test
        @DisplayName("Should refuse more than one PRIVATE KEY block")
        void shouldRefuseADuplicatedPrivateBlock() throws Exception {
            assertContentRefusal(TestSigningKeys.writeDuplicatedPrivateBlock(directory, TestSigningKeys.ecKeyPair()),
                    "holds more than one PRIVATE KEY block");
        }

        @Test
        @DisplayName("Should refuse more than one PUBLIC KEY block")
        void shouldRefuseADuplicatedPublicBlock() throws Exception {
            assertContentRefusal(TestSigningKeys.writeDuplicatedPublicBlock(directory, TestSigningKeys.ecKeyPair()),
                    "holds more than one PUBLIC KEY block");
        }

        @Test
        @DisplayName("Should refuse an encrypted block and name the conversion to unencrypted PKCS#8")
        void shouldRefuseAnEncryptedBlock() throws Exception {
            Path keyFile = TestSigningKeys.writeRelabelledPrivateBlock(directory, TestSigningKeys.rsaKeyPair(),
                    "ENCRYPTED PRIVATE KEY");

            assertContentRefusal(keyFile, "holds an ENCRYPTED PRIVATE KEY block; an encrypted key is not supported — "
                    + "convert it to an unencrypted PKCS#8 PRIVATE KEY block");
        }

        @Test
        @DisplayName("Should refuse a PKCS#1 RSA block and name the conversion to unencrypted PKCS#8")
        void shouldRefuseAnRsaPrivateKeyBlock() throws Exception {
            Path keyFile = TestSigningKeys.writeRelabelledPrivateBlock(directory, TestSigningKeys.rsaKeyPair(),
                    "RSA PRIVATE KEY");

            assertContentRefusal(keyFile, "holds a block labelled RSA PRIVATE KEY; that key format is not supported — "
                    + "convert it to an unencrypted PKCS#8 PRIVATE KEY block");
        }

        @Test
        @DisplayName("Should refuse a SEC1 EC block and name the conversion to unencrypted PKCS#8")
        void shouldRefuseAnEcPrivateKeyBlock() throws Exception {
            Path keyFile = TestSigningKeys.writeRelabelledPrivateBlock(directory, TestSigningKeys.ecKeyPair(),
                    "EC PRIVATE KEY");

            assertContentRefusal(keyFile, "holds a block labelled EC PRIVATE KEY; that key format is not supported — "
                    + "convert it to an unencrypted PKCS#8 PRIVATE KEY block");
        }

        @Test
        @DisplayName("Should refuse any other block label and name the label")
        void shouldRefuseAnotherBlockLabel() throws Exception {
            Path keyFile = TestSigningKeys.writeRelabelledPrivateBlock(directory, TestSigningKeys.ecKeyPair(),
                    "CERTIFICATE");

            assertContentRefusal(keyFile, "holds an unsupported PEM block 'CERTIFICATE'");
        }

        @Test
        @DisplayName("Should refuse a BEGIN line whose label is not a PEM label, without echoing it")
        void shouldRefuseAMalformedBeginLine() throws Exception {
            KeyPair keyPair = TestSigningKeys.ecKeyPair();
            Path keyFile = TestSigningKeys.writeContent(directory, TestSigningKeys.publicBlock(keyPair.getPublic())
                    + TestSigningKeys.pemBlock("private key", keyPair.getPrivate().getEncoded()));

            assertContentRefusal(keyFile, "holds a malformed PEM BEGIN line");
        }

        @Test
        @DisplayName("Should refuse content outside the two blocks")
        void shouldRefuseContentOutsideABlock() throws Exception {
            KeyPair keyPair = TestSigningKeys.ecKeyPair();
            Path keyFile = TestSigningKeys.writeContent(directory, "Bag Attributes: none\n"
                    + TestSigningKeys.privateBlock(keyPair.getPrivate())
                    + TestSigningKeys.publicBlock(keyPair.getPublic()));

            assertContentRefusal(keyFile, "holds content outside a PEM block");
        }

        @Test
        @DisplayName("Should refuse a block that is not closed by its own END line")
        void shouldRefuseAnUnclosedBlock() throws Exception {
            KeyPair keyPair = TestSigningKeys.ecKeyPair();
            String unclosed = TestSigningKeys.publicBlock(keyPair.getPublic()).replace("-----END PUBLIC KEY-----\n", "");
            Path keyFile = TestSigningKeys.writeContent(directory,
                    TestSigningKeys.privateBlock(keyPair.getPrivate()) + unclosed);

            assertContentRefusal(keyFile, "holds a PUBLIC KEY block that is not closed by its own END line");
        }

        @Test
        @DisplayName("Should refuse a block whose body is not base64")
        void shouldRefuseABlockThatIsNotBase64() throws Exception {
            KeyPair keyPair = TestSigningKeys.ecKeyPair();
            Path keyFile = TestSigningKeys.writeContent(directory, "-----BEGIN PRIVATE KEY-----\n"
                    + "@@@@ not base64 @@@@\n-----END PRIVATE KEY-----\n"
                    + TestSigningKeys.publicBlock(keyPair.getPublic()));

            assertContentRefusal(keyFile, "holds a PRIVATE KEY block that is not valid base64");
        }

        @Test
        @DisplayName("Should refuse a PRIVATE KEY block that no key factory accepts")
        void shouldRefuseABlockThatIsNoKey() throws Exception {
            KeyPair keyPair = TestSigningKeys.ecKeyPair();
            Path keyFile = TestSigningKeys.writeContent(directory, TestSigningKeys.pemBlock(
                    TestSigningKeys.PRIVATE_KEY_LABEL, new byte[48]) + TestSigningKeys.publicBlock(keyPair.getPublic()));

            assertContentRefusal(keyFile, "holds a PRIVATE KEY block that is neither an RSA nor an EC key");
        }
    }

    @Nested
    @DisplayName("Refusal of an unsupported or inconsistent key")
    class KeyRefusal {

        /**
         * The reason is one text for both purposes, so it must be true of both. The engine's
         * client-assertion signer does not sign {@code EdDSA} and its DPoP proof signer does, so a
         * reason naming either signer would be untrue for the other key; the refusal names the
         * gateway's own rule instead — both keys are held to the same two key types.
         */
        @ParameterizedTest(name = "{0}")
        @EnumSource(Purpose.class)
        @DisplayName("Should refuse an Ed25519 key for either purpose, naming the purpose's field and no signer")
        void shouldRefuseAnEd25519KeyForEitherPurpose(Purpose purpose) throws Exception {
            Path keyFile = TestSigningKeys.writeKeyFile(directory, TestSigningKeys.ed25519KeyPair());
            String configured = keyFile.toString();
            String field = switch (purpose) {
                case CLIENT_AUTHENTICATION -> CLIENT_AUTHENTICATION_FIELD;
                case SENDER_CONSTRAINT -> SENDER_CONSTRAINT_FIELD;
            };

            assertContentRefusal(keyFile, purpose, field, "holds an EdDSA key; EdDSA is not offered: both signing "
                    + "keys are held to the same two key types, RSA signing PS256 and EC on curve P-256 signing "
                    + "ES256 — provide an RSA key of at least 2048 bits or an EC key on curve P-256");
            IllegalStateException refused = assertThrows(IllegalStateException.class,
                    () -> ClientSigningKey.resolve(configured, purpose));
            assertFalse(refused.getMessage().contains("signer"),
                    "the reason names no signer, because no one signer is the reason for both keys: "
                            + refused.getMessage());
        }

        /**
         * The matched control for the reason above, read from the engine itself: its DPoP proof signer
         * accepts an Ed25519 key and its client-assertion signer refuses {@code EdDSA}. If either
         * changes, the refusal text is due for review.
         */
        @Test
        @DisplayName("Should find the engine signing EdDSA for a DPoP proof and refusing it for a client assertion")
        void shouldFindTheEngineSigningEdDsaForProofsOnly() {
            KeyPair ed25519 = TestSigningKeys.ed25519KeyPair();
            PrivateKey ed25519Private = ed25519.getPrivate();
            String clientId = Generators.letterStrings(8, 24).next();

            assertAll("EdDSA at the two engine signers",
                    () -> assertFalse(new DpopProofGenerator(ed25519, "EdDSA").jkt().isBlank(),
                            "the engine's proof signer accepts an Ed25519 key"),
                    () -> assertThrows(IllegalArgumentException.class,
                            () -> new PrivateKeyJwtAuth(clientId, "https://idp.example/realms/main",
                                    ed25519Private, "kid", "EdDSA"),
                            "the engine's client-assertion signer refuses EdDSA"));
        }

        @Test
        @DisplayName("Should refuse an EC key on a curve other than P-256")
        void shouldRefuseAnotherCurve() throws Exception {
            assertContentRefusal(TestSigningKeys.writeKeyFile(directory, TestSigningKeys.otherCurveKeyPair()),
                    "holds an EC key on a curve other than P-256");
        }

        @Test
        @DisplayName("Should refuse an RSA-1024 key, below the 2048-bit floor")
        void shouldRefuseAnUndersizedRsaKey() throws Exception {
            assertContentRefusal(TestSigningKeys.writeKeyFile(directory, TestSigningKeys.undersizedRsaKeyPair()),
                    "holds an RSA key with a modulus below 2048 bits");
        }

        @Test
        @DisplayName("Should refuse an RSA private half with an EC public half")
        void shouldRefuseAnRsaPrivateHalfWithAnEcPublicHalf() throws Exception {
            Path keyFile = TestSigningKeys.writeHalves(directory, TestSigningKeys.rsaKeyPair().getPrivate(),
                    TestSigningKeys.ecKeyPair().getPublic());

            assertContentRefusal(keyFile,
                    "holds a PRIVATE KEY block with an RSA key and a PUBLIC KEY block that is not an RSA public key");
        }

        @Test
        @DisplayName("Should refuse an EC private half with an RSA public half")
        void shouldRefuseAnEcPrivateHalfWithAnRsaPublicHalf() throws Exception {
            Path keyFile = TestSigningKeys.writeHalves(directory, TestSigningKeys.ecKeyPair().getPrivate(),
                    TestSigningKeys.rsaKeyPair().getPublic());

            assertContentRefusal(keyFile,
                    "holds a PRIVATE KEY block with an EC key and a PUBLIC KEY block that is not an EC public key");
        }

        @ParameterizedTest
        @EnumSource(KeyType.class)
        @DisplayName("Should refuse mismatched halves of one key type")
        void shouldRefuseMismatchedHalves(KeyType keyType) throws Exception {
            Path keyFile = TestSigningKeys.writeHalves(directory, keyType.generate().getPrivate(),
                    keyType.generate().getPublic());

            assertContentRefusal(keyFile,
                    "holds a PRIVATE KEY block and a PUBLIC KEY block that do not belong to the same key");
        }
    }

    @Nested
    @DisplayName("No key disclosure")
    class NoKeyDisclosure {

        @Test
        @DisplayName("Should render purpose, mode and algorithm only for a provided key")
        void shouldKeepAProvidedKeyOutOfToString() {
            Path keyFile = TestSigningKeys.writeKeyFile(directory, TestSigningKeys.rsaKeyPair());

            ClientSigningKey key = ClientSigningKey.resolve(keyFile.toString(), Purpose.CLIENT_AUTHENTICATION);

            assertAll("toString of a provided key",
                    () -> assertEquals("ClientSigningKey[purpose=client-authentication, mode=provided key file, "
                            + "algorithm=PS256]", key.toString(), "only purpose, mode and algorithm should be rendered"),
                    () -> assertFalse(key.toString().contains(key.keyId()), "the key id should not be rendered"),
                    () -> assertFalse(key.toString().contains((String) key.publicJwk().get("n")),
                            "no key member should be rendered"),
                    () -> assertFalse(key.toString().contains(keyFile.toString()), "the path should not be rendered"));
        }

        @Test
        @DisplayName("Should render purpose, mode and algorithm only for a generated key")
        void shouldKeepAGeneratedKeyOutOfToString() {
            ClientSigningKey key = ClientSigningKey.resolve(null, Purpose.SENDER_CONSTRAINT);

            assertAll("toString of a generated key",
                    () -> assertEquals("ClientSigningKey[purpose=sender-constraint, mode=generated on startup, "
                            + "algorithm=ES256]", key.toString(), "only purpose, mode and algorithm should be rendered"),
                    () -> assertFalse(key.toString().contains(key.keyId()), "the key id should not be rendered"),
                    () -> assertFalse(key.toString().contains((String) key.publicJwk().get("x")),
                            "no key member should be rendered"));
        }

        @Test
        @DisplayName("Should name each purpose's configuration field and bounded log label exactly")
        void shouldCarryTheFieldAndLabelOfEachPurpose() {
            assertAll("purposes",
                    () -> assertEquals(CLIENT_AUTHENTICATION_FIELD, Purpose.CLIENT_AUTHENTICATION.configField(),
                            "the client-authentication field should be named"),
                    () -> assertEquals("client-authentication", Purpose.CLIENT_AUTHENTICATION.logLabel(),
                            "the client-authentication label should be bounded"),
                    () -> assertEquals(SENDER_CONSTRAINT_FIELD, Purpose.SENDER_CONSTRAINT.configField(),
                            "the sender-constraint field should be named"),
                    () -> assertEquals("sender-constraint", Purpose.SENDER_CONSTRAINT.logLabel(),
                            "the sender-constraint label should be bounded"));
        }
    }
}
